projectVersion=5.0.0-SNAPSHOT
grailsVersion=7.0.0-SNAPSHOT

# The bom will pull 6.x because it's inherited from spring, and we do not override it.
hibernateVersion=5.6.15.Final

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M